name: Wonder
title: Wonder | Wonder is wonderful
description: 그냥 메모장
tags:
  - notepad
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: jangwd88@gmail.com
disqus_username: ""
